# Generated by Django 4.2.4 on 2023-08-16 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_category_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon_url',
            field=models.CharField(default='', max_length=1024),
        ),
    ]
