# Generated by Django 4.2.4 on 2023-08-20 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_description_alter_product_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='gender',
            field=models.CharField(default='Male', max_length=50),
        ),
    ]
