# Generated by Django 4.2.4 on 2023-08-15 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_actual_price_product_brand_product_category_and_more'),
        ('user_details', '0002_searchquery_reviews_purchasehistory_favourites'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Favourites',
            new_name='Favourite',
        ),
        migrations.RenameModel(
            old_name='Reviews',
            new_name='Review',
        ),
    ]
