# Generated by Django 4.2.4 on 2023-08-16 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_actual_price_product_brand_product_category_and_more'),
        ('user_details', '0003_rename_favourites_favourite_rename_reviews_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('user_detail', models.ManyToManyField(to='user_details.userdetail')),
            ],
        ),
    ]
