# Generated by Django 4.2.4 on 2023-08-16 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_category_icon_url'),
        ('user_details', '0005_review_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='product',
        ),
        migrations.RemoveField(
            model_name='review',
            name='user_detail',
        ),
        migrations.AddField(
            model_name='review',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='user_detail',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user_details.userdetail'),
            preserve_default=False,
        ),
    ]
